export const pizzas = [
    {
        id: "1",
        nombre: "Pizza Napolitana",
        imagen: "https://firebasestorage.googleapis.com/v0/b/apis-varias-mias.appspot.com/o/pizzeria%2Fpizza-1239077_640_cl.jpg?alt=media&token=6a9a33da-5c00-49d4-9080-784dcc87ec2c",
        precio: 5590,
        stock: 100,
        disponibilidad: "En stock",
        ingredientes: ["Mozzarella", "Tomates", "Jamón", "Orégano"],
    },
    {
        id: "2",
        nombre: "Pizza Española",
        imagen: "https://firebasestorage.googleapis.com/v0/b/apis-varias-mias.appspot.com/o/pizzeria%2Fcheese-164872_640_com.jpg?alt=media&token=18b2b821-4d0d-43f2-a1c6-8c57bc388fab",
        precio: 6590,
        stock: 50,
        disponibilidad: "En stock",
        ingredientes: ["Mozzarella", "Gorgonzola", "Parmesano", "Provolone"],
    },
    {
        id: "3",
        nombre: "Pizza Pepperoni",
        imagen: "https://firebasestorage.googleapis.com/v0/b/apis-varias-mias.appspot.com/o/pizzeria%2Fpizza-1239077_640_com.jpg?alt=media&token=e7cde87a-08d5-4040-ac54-90f6c31eb3e3",
        precio: 6500,
        stock: 0,
        disponibilidad: "Agotado",
        ingredientes: ["Mozzarella", "Pepperoni", "Orégano"],
    },    
    {
        id: "4",
        nombre: "Pizza Napolitana XL",
        imagen: "https://firebasestorage.googleapis.com/v0/b/apis-varias-mias.appspot.com/o/pizzeria%2Fpizza-1239077_640_cl.jpg?alt=media&token=6a9a33da-5c00-49d4-9080-784dcc87ec2c",
        precio: 8590,
        stock: 100,
        disponibilidad: "En stock",
        ingredientes: ["Mozzarella", "Tomates", "Jamón", "Orégano"],
    },
    {
        id: "5",
        nombre: "Pizza Española XL",
        imagen: "https://firebasestorage.googleapis.com/v0/b/apis-varias-mias.appspot.com/o/pizzeria%2Fcheese-164872_640_com.jpg?alt=media&token=18b2b821-4d0d-43f2-a1c6-8c57bc388fab",
        precio: 9050,
        stock: 50,
        disponibilidad: "En stock",
        ingredientes: ["Mozzarella", "Gorgonzola", "Parmesano", "Provolone"],
    },
    {
        id: "6",
        nombre: "Pizza Pepperoni XL",
        imagen: "https://firebasestorage.googleapis.com/v0/b/apis-varias-mias.appspot.com/o/pizzeria%2Fpizza-1239077_640_com.jpg?alt=media&token=e7cde87a-08d5-4040-ac54-90f6c31eb3e3",
        precio: 8750,
        stock: 0,
        disponibilidad: "Agotado",
        ingredientes: ["Mozzarella", "Pepperoni", "Orégano"],
    },
];